### ISSUE TITLE
向大佬，请教学习经验

### ISSUE THREAD

**Issue by 1391020381** [yanlele/node-index#2]
和你差不多一样的工作时间，你的执行力很强！你是通过什么方法来确保，计划的执行？希望向你多学习，大佬也多分享下经验，看到你的那么多项目真实惭愧。

**Comment by yanlele** [comment]
我也已经感觉自己要废了、、、、、
早年的时候， 单纯凭借爱发电。时间就了， 动力也没得多少了。
